---
# defaults file for buildvm

buildvm_netbox_api: "{{ lookup('env', 'NETBOX_API') }}"
buildvm_netbox_api_key: "{{ lookup('env', 'NETBOX_API_TOKEN') }}"
buildvm_netbox_validcert: "{{ lookup('env', 'NETBOX_VALID_HTTPS') | bool | default(true) }}"

# This is the tag that is added to all items configured by this role.
# We do this so users of Netbox know not to alter items with this tag.
# If you do not want to use this feature, simply comment out the lines below.
buildvm_tags_base: "{{ netbox_tags_base | default(['ansible_managed', 'terraform_managed']) | list }}"
buildvm_netbox_version: "{{ netbox_version | default(4) }}"
buildvm_cluster_type: proxmox  # we use this to validate that the cluster type in Netbox is what we expect
